apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      securityContext:
        fsGroup: 1000  # Nexus'un dosyalara yazabilmesi için gerekli olan grup kimliği
      containers:
      - name: nexus
        image: sonatype/nexus3:latest
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
        securityContext:
          runAsUser: 1000  # Nexus container'ının çalışacağı kullanıcı kimliği
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-pvc
