apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  namespace: nexus
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/nexus"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: nexus-pvc
    namespace: nexus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: nexus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: nexus-pv
